#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# (C) Copyright 2018 SATO Corporation.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := fx3lx.o

obj-y  += ../../freescale/common/
